### PR TITLE
Add unary concurrency test

### PR DESCRIPTION
**Pull request by psalin**
Test for #39

### CODE REVIEW

**Comment by psalin** [comment]
Only 1 out of 3 failed, multiple messages may need to be sent per process in order to catch this more reliably.

**Comment by tsloughter** [comment]
Thanks! And maybe can just use common test's features to rerun tests until they pass to keep it running again and again.

**Comment by psalin** [comment]
Ok, do you mean putting the concurrent test in its own group and using {repeat_until_any_fail, N} for it?

**Comment by tsloughter** [comment]
@psalin yea

**Comment by psalin** [comment]
I updated the test and it revealed a server side concurrency issue and that the client will crash when that occurs, I created issues for those.

**Comment by tsloughter** [comment]
Ok, cool, will get those fixed early this week most likely.

**Comment by tsloughter** [comment]
Thanks, this was merged in with #47

**Pull request closed without merging**
