### PR TITLE
Fix types ctx:ctx() -> ctx:t()

### PR DESCRIPTION
**Pull request by juise**

### CODE REVIEW

**Comment by tsloughter** [comment]
Is the dialyzer failure here related to your PR on the ctx lib?

**Comment by juise** [comment]
Yes, I've got the following warings:

```
===> Analyzing 54 files with _build/default/rebar3_25.0.2_plt...
_build/default/lib/ctx/src/ctx.erl
Line 21 Column 28: Unknown type timer:time/0
Line 21 Column 42: Unknown type timer:time/0
_build/default/lib/grpcbox/src/grpcbox_stream.erl
Line 42 Column 40: Unknown type ctx:ctx/0
```

**Comment by juise** [comment]
@tsloughter any updates?

**Comment by tsloughter** [comment]
Hey, sorry, I'm merging this once it passes CI. Thanks!

**Comment by tsloughter** [comment]
Dialyzer is still failing.

**Comment by tsloughter** [comment]
Thanks!

**Pull request merged**
